spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.207.128:3306/test?useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.jrx.zyh.model

